#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD97BUN import recorddefs

# Adjusted for Daimler VDA007_v1.14
# # NN means NotNeeded 
# # OK when segment is the same as standard 
# # CH blabla what is changed in the line


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 0, MAX: 1}, # CH MIN:1->0, testcase Standard VDA007 with one vehicle in Documentation EDIFACT VDA007 V1.14.pdf
    # NN {ID: 'CTA', MIN: 0, MAX: 1},
    # NN {ID: 'COM', MIN: 0, MAX: 9},
    # NN {ID: 'DTM', MIN: 0, MAX: 9},
    # NN {ID: 'TSR', MIN: 0, MAX: 9},
    # NN {ID: 'CUX', MIN: 0, MAX: 9},
    # NN {ID: 'MOA', MIN: 0, MAX: 99},
    # NN {ID: 'FTX', MIN: 0, MAX: 99},
    # NN {ID: 'CNT', MIN: 0, MAX: 9},
    # NN {ID: 'DOC', MIN: 0, MAX: 9},
    # NN {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
    # NN     {ID: 'DTM', MIN: 0, MAX: 9},
    # NN ]},
	{ID: 'TOD', MIN: 0, MAX: 1}, # CH MAX2->1, no subsegments
    # CH orig {ID: 'TOD', MIN: 0, MAX: 2, LEVEL: [
    # NN     {ID: 'LOC', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'RFF', MIN: 0, MAX: 999, LEVEL: [
    # NN     {ID: 'DTM', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'GOR', MIN: 0, MAX: 9, LEVEL: [
    # NN     {ID: 'DTM', MIN: 0, MAX: 9},
    # NN     {ID: 'LOC', MIN: 0, MAX: 9},
    # NN     {ID: 'SEL', MIN: 0, MAX: 9},
    # NN     {ID: 'FTX', MIN: 0, MAX: 9},
    # NN     {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN         {ID: 'DTM', MIN: 0, MAX: 1},
    # NN     ]},
    # NN ]},
    # NN {ID: 'CPI', MIN: 0, MAX: 9, LEVEL: [
    # NN     {ID: 'RFF', MIN: 0, MAX: 99},
    # NN     {ID: 'CUX', MIN: 0, MAX: 1},
    # NN     {ID: 'LOC', MIN: 0, MAX: 9},
    # NN     {ID: 'MOA', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN    {ID: 'LOC', MIN: 0, MAX: 1},
    # NN     {ID: 'FTX', MIN: 0, MAX: 1},
    # NN     {ID: 'CUX', MIN: 0, MAX: 1},
    # NN     {ID: 'PRI', MIN: 0, MAX: 1},
    # NN     {ID: 'EQN', MIN: 0, MAX: 1},
    # NN     {ID: 'PCD', MIN: 0, MAX: 1},
    # NN     {ID: 'MOA', MIN: 0, MAX: 9},
    # NN     {ID: 'QTY', MIN: 0, MAX: 9},
    # NN ]},
    {ID: 'TDT', MIN: 0, MAX: 2, LEVEL: [ # CH MAX99->2  segment 16 & segment 29 in Documentation EDIFACT VDA007 V1.14.pdf
        # NN {ID: 'DTM', MIN: 0, MAX: 9},
        # NN {ID: 'TSR', MIN: 0, MAX: 9},
        {ID: 'LOC', MIN: 0, MAX: 2, LEVEL: [ # CH MAX99->2
            {ID: 'DTM', MIN: 0, MAX: 1}, # CH MAX9->1
        ]},
		{ID: 'RFF', MIN: 0, MAX: 2}, # CH MAX2->1, no subsegments
        # CH orig {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
        # NN    {ID: 'DTM', MIN: 0, MAX: 1},
        # NN ]},
    ]},
	{ID: 'NAD', MIN: 1, MAX: 1},# CH MAX99->1, no subsegments
    # CH orig {ID: 'NAD', MIN: 1, MAX: 99, LEVEL: [
    # NN      {ID: 'LOC', MIN: 0, MAX: 9},
    # NN      {ID: 'MOA', MIN: 0, MAX: 9},
    # NN      {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
    # NN          {ID: 'COM', MIN: 0, MAX: 9},
    # NN      ]},
    # NN      {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN          {ID: 'DTM', MIN: 0, MAX: 1},
    # NN      ]},
    # NN      {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN          {ID: 'CUX', MIN: 0, MAX: 1},
    # NN          {ID: 'PRI', MIN: 0, MAX: 1},
    # NN          {ID: 'EQN', MIN: 0, MAX: 1},
    # NN          {ID: 'PCD', MIN: 0, MAX: 1},
    # NN          {ID: 'MOA', MIN: 0, MAX: 9},
    # NN          {ID: 'QTY', MIN: 0, MAX: 9},
    # NN      ]},
    # NN      {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
    # NN          {ID: 'DTM', MIN: 0, MAX: 9},
    # NN      ]},
    # NN      {ID: 'CPI', MIN: 0, MAX: 9, LEVEL: [
    # NN          {ID: 'RFF', MIN: 0, MAX: 99},
    # NN          {ID: 'CUX', MIN: 0, MAX: 1},
    # NN          {ID: 'LOC', MIN: 0, MAX: 9},
    # NN          {ID: 'MOA', MIN: 0, MAX: 9},
    # NN      ]},
    # NN      {ID: 'TSR', MIN: 0, MAX: 99, LEVEL: [
    # NN          {ID: 'RFF', MIN: 0, MAX: 1},
    # NN          {ID: 'LOC', MIN: 0, MAX: 1},
    # NN          {ID: 'TPL', MIN: 0, MAX: 1},
    # NN          {ID: 'FTX', MIN: 0, MAX: 9},
    # NN      ]},
    # NN  ]},
    {ID: 'GID', MIN: 0, MAX: 1, LEVEL: [ # CH MAX999->1
    # NN     {ID: 'HAN', MIN: 0, MAX: 99},
    # NN     {ID: 'TMP', MIN: 0, MAX: 1},
    # NN     {ID: 'RNG', MIN: 0, MAX: 1},
    # NN     {ID: 'TMD', MIN: 0, MAX: 1},
        {ID: 'LOC', MIN: 0, MAX: 1}, # CH MAX9->1
    # NN     {ID: 'MOA', MIN: 0, MAX: 9},
        {ID: 'PIA', MIN: 0, MAX: 1}, # CH MAX9->1
        {ID: 'FTX', MIN: 0, MAX: 112}, # CH MAX99->112,comment  Segment 48 (1) + Segment 49 (?) + Segment 50 (30) + Segment 53 (20) + Segment 54 (20) + Segment 56 (20) + Segment 57 (20) 
    # NN         {ID: 'PCD', MIN: 0, MAX: 9},
    # NN         {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
    # NN             {ID: 'DTM', MIN: 0, MAX: 1},
    # NN         ]},
        {ID: 'GDS', MIN: 0, MAX: 1},# CH MAX9->1
		{ID: 'MEA', MIN: 0, MAX: 1},# CH MAX99->1, no subsegments
    # CH orig     {ID: 'MEA', MIN: 0, MAX: 99, LEVEL: [
    # NN         {ID: 'EQN', MIN: 0, MAX: 1},
    # NN     ]},
    # NN     {ID: 'DIM', MIN: 0, MAX: 99, LEVEL: [
    # NN         {ID: 'EQN', MIN: 0, MAX: 1},
    # NN     ]},
        {ID: 'RFF', MIN: 0, MAX: 11, LEVEL: [# CH MAX9->11
            {ID: 'DTM', MIN: 0, MAX: 1},# CH MAX9->1
        ]},
        {ID: 'PCI', MIN: 0, MAX: 1, LEVEL: [ # CH MAX999->1
    # NN         {ID: 'RFF', MIN: 0, MAX: 1},
    # NN         {ID: 'DTM', MIN: 0, MAX: 1},
            {ID: 'GIN', MIN: 0, MAX: 3},# CH MAX10->3
        ]},
    # NN     {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN         {ID: 'DTM', MIN: 0, MAX: 9},
    # NN     ]},
    # NN     {ID: 'GOR', MIN: 0, MAX: 9, LEVEL: [
    # NN         {ID: 'DTM', MIN: 0, MAX: 9},
    # NN         {ID: 'LOC', MIN: 0, MAX: 9},
    # NN         {ID: 'SEL', MIN: 0, MAX: 9},
    # NN         {ID: 'FTX', MIN: 0, MAX: 9},
    # NN         {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN             {ID: 'DTM', MIN: 0, MAX: 1},
    # NN         ]},
    # NN     ]},
    # NN     {ID: 'TPL', MIN: 0, MAX: 9, LEVEL: [
    # NN         {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN             {ID: 'EQN', MIN: 0, MAX: 1},
    # NN         ]},
    # NN     ]},
		{ID: 'SGP', MIN: 0, MAX: 1},# CH MAX999->1, no subsegments
    # CH orig     {ID: 'SGP', MIN: 0, MAX: 999, LEVEL: [
    # NN        {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        ]},
    # NN    ]},
    # NN    {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'CUX', MIN: 0, MAX: 1},
    # NN        {ID: 'PRI', MIN: 0, MAX: 1},
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        {ID: 'PCD', MIN: 0, MAX: 1},
    # NN        {ID: 'MOA', MIN: 0, MAX: 9},
    # NN        {ID: 'QTY', MIN: 0, MAX: 9},
    # NN        {ID: 'LOC', MIN: 0, MAX: 9},
    # NN    ]},
		{ID: 'DGS', MIN: 0, MAX: 1},# CH MAX9->1, no subsegments
    # CH orig    {ID: 'DGS', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'FTX', MIN: 0, MAX: 99},
    # NN        {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'COM', MIN: 0, MAX: 9},
    # NN        ]},
    # NN        {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        ]},
    # NN        {ID: 'SGP', MIN: 0, MAX: 999, LEVEL: [
    # NN            {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN                {ID: 'EQN', MIN: 0, MAX: 1},
    # NN            ]},
    # NN        ]},
        ]},
    ]},
    # NN {ID: 'EQD', MIN: 0, MAX: 999, LEVEL: [
    # NN    {ID: 'EQN', MIN: 0, MAX: 1},
    # NN    {ID: 'TMD', MIN: 0, MAX: 1},
    # NN    {ID: 'MEA', MIN: 0, MAX: 9},
    # NN    {ID: 'DIM', MIN: 0, MAX: 9},
    # NN    {ID: 'SEL', MIN: 0, MAX: 99},
    # NN    {ID: 'TPL', MIN: 0, MAX: 9},
   # NN     {ID: 'HAN', MIN: 0, MAX: 1},
    # NN    {ID: 'TMP', MIN: 0, MAX: 1},
    # NN    {ID: 'FTX', MIN: 0, MAX: 9},
    # NN    {ID: 'RFF', MIN: 0, MAX: 9},
   # NN     {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'CUX', MIN: 0, MAX: 1},
    # NN        {ID: 'PRI', MIN: 0, MAX: 1},
   # NN         {ID: 'EQN', MIN: 0, MAX: 1},
   # NN         {ID: 'PCD', MIN: 0, MAX: 1},
   # NN         {ID: 'MOA', MIN: 0, MAX: 9},
   # NN         {ID: 'QTY', MIN: 0, MAX: 9},
    # NN    ]},
   # NN     {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 1},
    # NN        {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'COM', MIN: 0, MAX: 9},
   # NN         ]},
   # NN     ]},
    # NN    {ID: 'EQA', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN    ]},
    # NN]},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
