#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD97BUN import recorddefs

# Adjusted for Daimler VDA008_v1.2
# # NN means NotNeeded 
# # OK when segment is the same as standard 
# # CH blabla what is changed in the line


structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    # NN {ID: 'CTA', MIN: 0, MAX: 1},
    # NN {ID: 'COM', MIN: 0, MAX: 9},
    {ID: 'DTM', MIN: 0, MAX: 9}, #CH  appear ??
    # NN {ID: 'TSR', MIN: 0, MAX: 9},
    # NN {ID: 'CUX', MIN: 0, MAX: 9},
    # NN {ID: 'MOA', MIN: 0, MAX: 99},
    # NN {ID: 'FTX', MIN: 0, MAX: 99},
    # NN {ID: 'CNT', MIN: 0, MAX: 9},
    # NN {ID: 'DOC', MIN: 0, MAX: 9},
    # NN {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [
    # NN     {ID: 'DTM', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'TOD', MIN: 0, MAX: 2, LEVEL: [
    # NN     {ID: 'LOC', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'RFF', MIN: 0, MAX: 999, LEVEL: [
    # NN     {ID: 'DTM', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'GOR', MIN: 0, MAX: 9, LEVEL: [
    # NN     {ID: 'DTM', MIN: 0, MAX: 9},
    # NN     {ID: 'LOC', MIN: 0, MAX: 9},
    # NN     {ID: 'SEL', MIN: 0, MAX: 9},
    # NN     {ID: 'FTX', MIN: 0, MAX: 9},
    # NN     {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN         {ID: 'DTM', MIN: 0, MAX: 1},
    # NN     ]},
    # NN ]},
    # NN {ID: 'CPI', MIN: 0, MAX: 9, LEVEL: [
    # NN     {ID: 'RFF', MIN: 0, MAX: 99},
    # NN     {ID: 'CUX', MIN: 0, MAX: 1},
    # NN     {ID: 'LOC', MIN: 0, MAX: 9},
    # NN     {ID: 'MOA', MIN: 0, MAX: 9},
    # NN ]},
    # NN {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN     {ID: 'LOC', MIN: 0, MAX: 1},
    # NN     {ID: 'FTX', MIN: 0, MAX: 1},
    # NN     {ID: 'CUX', MIN: 0, MAX: 1},
    # NN     {ID: 'PRI', MIN: 0, MAX: 1},
    # NN     {ID: 'EQN', MIN: 0, MAX: 1},
    # NN     {ID: 'PCD', MIN: 0, MAX: 1},
    # NN     {ID: 'MOA', MIN: 0, MAX: 9},
    # NN     {ID: 'QTY', MIN: 0, MAX: 9},
    # NN ]},
    {ID: 'TDT', MIN: 0, MAX: 1, LEVEL: [ # CH MAX99->1
    # NN    {ID: 'DTM', MIN: 0, MAX: 9},
    # NN   {ID: 'TSR', MIN: 0, MAX: 9},
        {ID: 'LOC', MIN: 0, MAX: 99, LEVEL: [ #CH  appear ??
            {ID: 'DTM', MIN: 0, MAX: 9}, #CH  appear ??
        ]},
    # NN    {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 1},
    # NN    ]},
    ]},
	{ID: 'NAD', MIN: 1, MAX: 1},# CH MAX99->1,no subsegments
    # CH orig{ID: 'NAD', MIN: 1, MAX: 99, LEVEL: [
    # NN    {ID: 'LOC', MIN: 0, MAX: 9},
    # NN    {ID: 'MOA', MIN: 0, MAX: 9},
    # NN    {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'COM', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 1},
    # NN    ]},
    # NN    {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'CUX', MIN: 0, MAX: 1},
    # NN        {ID: 'PRI', MIN: 0, MAX: 1},
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        {ID: 'PCD', MIN: 0, MAX: 1},
    # NN        {ID: 'MOA', MIN: 0, MAX: 9},
    # NN        {ID: 'QTY', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'CPI', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'RFF', MIN: 0, MAX: 99},
    # NN        {ID: 'CUX', MIN: 0, MAX: 1},
    # NN        {ID: 'LOC', MIN: 0, MAX: 9},
    # NN        {ID: 'MOA', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'TSR', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'RFF', MIN: 0, MAX: 1},
    # NN        {ID: 'LOC', MIN: 0, MAX: 1},
    # NN        {ID: 'TPL', MIN: 0, MAX: 1},
    # NN        {ID: 'FTX', MIN: 0, MAX: 9},
    # NN    ]},
    # NN]},
    {ID: 'GID', MIN: 0, MAX: 1, LEVEL: [ # CH MAX999->1
    # NN    {ID: 'HAN', MIN: 0, MAX: 99},
    # NN    {ID: 'TMP', MIN: 0, MAX: 1},
    # NN    {ID: 'RNG', MIN: 0, MAX: 1},
    # NN    {ID: 'TMD', MIN: 0, MAX: 1},
        {ID: 'LOC', MIN: 0, MAX: 9},# CH ?? in Documentation EDIFACT VDA008_V1.2.pdf
    # NN    {ID: 'MOA', MIN: 0, MAX: 9},
    # NN    {ID: 'PIA', MIN: 0, MAX: 9},
    # NN    {ID: 'FTX', MIN: 0, MAX: 99},
    # NN   {ID: 'PCD', MIN: 0, MAX: 9},
    # NN    {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 1},
    # NN    ]},
        {ID: 'GDS', MIN: 0, MAX: 1},# CH MAX9->1
    # NN    {ID: 'MEA', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN    ]},
    # NN    {ID: 'DIM', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN    ]},
		{ID: 'RFF', MIN: 0, MAX: 9},# CH MAX9->11, no subsegments 
    # NN    {ID: 'RFF', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 9},
    # NN    ]},
        {ID: 'PCI', MIN: 0, MAX: 1, LEVEL: [ # CH MAX999->1
    # NN        {ID: 'RFF', MIN: 0, MAX: 1},
    # NN        {ID: 'DTM', MIN: 0, MAX: 1},
            {ID: 'GIN', MIN: 0, MAX: 3},# CH MAX10->3
        ]},
    # NN    {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'GOR', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 9},
    # NN        {ID: 'LOC', MIN: 0, MAX: 9},
    # NN        {ID: 'SEL', MIN: 0, MAX: 9},
    # NN        {ID: 'FTX', MIN: 0, MAX: 9},
    # NN        {ID: 'DOC', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'DTM', MIN: 0, MAX: 1},
    # NN        ]},
    # NN    ]},
    # NN    {ID: 'TPL', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        ]},
    # NN    ]},
    # NN    {ID: 'SGP', MIN: 0, MAX: 999, LEVEL: [
    # NN        {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        ]},
    # NN    ]},
    # NN    {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'CUX', MIN: 0, MAX: 1},
    # NN        {ID: 'PRI', MIN: 0, MAX: 1},
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        {ID: 'PCD', MIN: 0, MAX: 1},
    # NN        {ID: 'MOA', MIN: 0, MAX: 9},
    # NN        {ID: 'QTY', MIN: 0, MAX: 9},
    # NN        {ID: 'LOC', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'DGS', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'FTX', MIN: 0, MAX: 99},
    # NN        {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'COM', MIN: 0, MAX: 9},
    # NN        ]},
    # NN        {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        ]},
    # NN        {ID: 'SGP', MIN: 0, MAX: 999, LEVEL: [
    # NN            {ID: 'MEA', MIN: 0, MAX: 9, LEVEL: [
    # NN                {ID: 'EQN', MIN: 0, MAX: 1},
    # NN            ]},
    # NN        ]},
    # NN    ]},
    ]},	
    # NN {ID: 'EQD', MIN: 0, MAX: 999, LEVEL: [
    # NN    {ID: 'EQN', MIN: 0, MAX: 1},
    # NN    {ID: 'TMD', MIN: 0, MAX: 1},
    # NN    {ID: 'MEA', MIN: 0, MAX: 9},
    # NN    {ID: 'DIM', MIN: 0, MAX: 9},
    # NN    {ID: 'SEL', MIN: 0, MAX: 99},
    # NN    {ID: 'TPL', MIN: 0, MAX: 9},
    # NN    {ID: 'HAN', MIN: 0, MAX: 1},
    # NN    {ID: 'TMP', MIN: 0, MAX: 1},
    # NN    {ID: 'FTX', MIN: 0, MAX: 9},
    # NN    {ID: 'RFF', MIN: 0, MAX: 9},
    # NN    {ID: 'TCC', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'CUX', MIN: 0, MAX: 1},
    # NN        {ID: 'PRI', MIN: 0, MAX: 1},
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN        {ID: 'PCD', MIN: 0, MAX: 1},
    # NN        {ID: 'MOA', MIN: 0, MAX: 9},
    # NN        {ID: 'QTY', MIN: 0, MAX: 9},
    # NN    ]},
    # NN    {ID: 'NAD', MIN: 0, MAX: 9, LEVEL: [
    # NN        {ID: 'DTM', MIN: 0, MAX: 1},
    # NN        {ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
    # NN            {ID: 'COM', MIN: 0, MAX: 9},
    # NN        ]},
    # NN    ]},
    # NN    {ID: 'EQA', MIN: 0, MAX: 99, LEVEL: [
    # NN        {ID: 'EQN', MIN: 0, MAX: 1},
    # NN    ]},
    # NN ]},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
