#Generated by bots open source edi translator from UN-docs.
from bots.botsconfig import *
from edifact import syntax
from recordsD97BUN import recorddefs

# Adjusted for Daimler VDA006 v1.09
# # NN means NotNeeded 
# # OK when segment is the same as standard 
# # CH blabla what is changed in the line

structure = [
{ID: 'UNH', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'BGM', MIN: 1, MAX: 1},
    # NN {ID: 'DTM', MIN: 0, MAX: 9},
    # NN {ID: 'TSR', MIN: 0, MAX: 1},
	{ID: 'NAD', MIN: 0, MAX: 1},# CH MAX:9->1, no subsegments
    # CH orig {ID: 'NAD', MIN: 0, MAX: 1, LEVEL: [ # CH MAX:9->1
        # NN{ID: 'CTA', MIN: 0, MAX: 9, LEVEL: [
        # NN    {ID: 'COM', MIN: 0, MAX: 9},
        # NN]},
    # NN]},
    {ID: 'RFF', MIN: 0, MAX: 1, LEVEL: [ # CH MAX:9->1,  comment This segment may not appear by railway transport
        {ID: 'DTM', MIN: 0, MAX: 1},
    ]},
    # NN{ID: 'LOC', MIN: 0, MAX: 9},
    # NN{ID: 'FTX', MIN: 0, MAX: 9},
    # NN {ID: 'CNT', MIN: 0, MAX: 9},
    # NN {ID: 'CNI', MIN: 0, MAX: 999, LEVEL: [
        # NN {ID: 'LOC', MIN: 0, MAX: 9},
        # NN {ID: 'CNT', MIN: 0, MAX: 9},
        # NN {ID: 'STS', MIN: 1, MAX: 99, LEVEL: [
            # NN {ID: 'RFF', MIN: 0, MAX: 9},
            # NN {ID: 'DTM', MIN: 0, MAX: 9},
            # NN {ID: 'DOC', MIN: 0, MAX: 1},
            # NN {ID: 'FTX', MIN: 0, MAX: 9},
            # NN {ID: 'NAD', MIN: 0, MAX: 9},
            # NN {ID: 'LOC', MIN: 0, MAX: 1},
            # NN {ID: 'PCI', MIN: 0, MAX: 99},
            {ID: 'TDT', MIN: 0, MAX: 1, LEVEL: [ # CH MAX:99->1
                {ID: 'RFF', MIN: 0, MAX: 1}, # CH MAX:9->1
                {ID: 'LOC', MIN: 0, MAX: 1}, # CH MAX:9->1
                # NN {ID: 'DTM', MIN: 0, MAX: 9},
            ]},
			{ID: 'EQD', MIN: 0, MAX: 1} # CH MAX:99->1,no subsegments
            # CH orig {ID: 'EQD', MIN: 0, MAX: 99, LEVEL: [ 
                # NN {ID: 'MEA', MIN: 0, MAX: 9},
                # NN {ID: 'DIM', MIN: 0, MAX: 9},
                # NN {ID: 'SEL', MIN: 0, MAX: 9},
                # NN {ID: 'RFF', MIN: 0, MAX: 9},
                # NN {ID: 'TPL', MIN: 0, MAX: 9},
                # NN {ID: 'TMD', MIN: 0, MAX: 1},
                # NN {ID: 'EQA', MIN: 0, MAX: 99, LEVEL: [
                    # NN {ID: 'SEL', MIN: 0, MAX: 9},
                # NN ]},
            # NN ]},
            {ID: 'GID', MIN: 0, MAX: 99, LEVEL: [ # comment once per wehicle
                # NN {ID: 'HAN', MIN: 0, MAX: 9},
                # NN {ID: 'SGP', MIN: 0, MAX: 99},
                # NN {ID: 'DGS', MIN: 0, MAX: 9},
                # NN {ID: 'FTX', MIN: 0, MAX: 9},
                # NN {ID: 'MEA', MIN: 0, MAX: 99, LEVEL: [
                    # NN {ID: 'EQN', MIN: 0, MAX: 1},
                # NN ]},
                # NN {ID: 'DIM', MIN: 0, MAX: 99, LEVEL: [
                    # NN {ID: 'EQN', MIN: 0, MAX: 1},
                # NN ]},
                {ID: 'PCI', MIN: 0, MAX: 1, LEVEL: [ # CH MAX:99->1
                    {ID: 'GIN', MIN: 0, MAX: 1}, # CH MAX:9->1
                ]},
            ]},
        # NN ]},
    # NN ]},
    {ID: 'UNT', MIN: 1, MAX: 1},
]},
]
